name: .NET

on:
  push:
    tags:
      - "*"

jobs:
  release-console:
    name: Release Console
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        targets: [linux-x64, win-x64]
    with:
      project_name: Console
      project_path: TwitchDropsBot.Console/TwitchDropsBot.Console.csproj
      framework: net8.0
      os: ubuntu-latest
      target: ${{ matrix.targets }}

  release-winforms:
    name: Release WinForms
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        targets: [win-x64]
    with:
      project_name: WinForms
      project_path: TwitchDropsBot.WinForms/TwitchDropsBot.WinForms.csproj
      framework: net8.0-windows
      os: windows-latest
      target: ${{ matrix.targets }}

  release-gtk:
    name: Release GTK
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        targets: [linux-x64, win-x64]
    with:
      project_name: GTK
      project_path: TwitchDropsBot.GTK/TwitchDropsBot.GTK.csproj
      framework: net8.0
      os: ubuntu-latest
      target: ${{ matrix.targets }}
